language: "perl"
sudo: false
perl:
# - "5.6.2"
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.22-thr"
  - "dev"
  - "blead"

addons:
  apt:
    packages:
    - gperf

# blead and 5.6 stumble over YAML and more missing dependencies
# for Devel::Cover::Report::Coveralls
before_install:
  - cpanm Module::Signature
install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - export AUTOMATED_TESTING=1 HARNESS_TIMER=1 AUTHOR_TESTING=0 RELEASE_TESTING=0
  - cpan-install --deps

# cpanm does not 5.6
before_script:
  - gperf --version

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  fast_finish: true
  allow_failures:
    - perl: "dev"
    - perl: "blead"
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting

# Hack to not run on tag pushes:
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/
